name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  hello-jobs:
    runs-on: ubuntu-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions"